// Code generated by annotation-gen. DO NOT EDIT.
package runtime

import (
	"github.com/duxweb/go-fast/v2/annotation"
	AppSystemAdmin "example/app/system/admin"
	AppSystemModels "example/app/system/models"
	AppSystemWeb "example/app/system/web"
)

// GetAnnotations 返回所有注解的索引
func GetAnnotations() []*annotation.File {
	return []*annotation.File{
		{
			Name: "app/system/admin/bookRes.go",
			Annotations: []*annotation.Annotation{
				{
					Name: "Resource",
					Params: map[string]any{
					},
					Func: AppSystemAdmin.BookRes,
				},
			},
		},
		{
			Name: "app/system/models/book.go",
			Annotations: []*annotation.Annotation{
				{
					Name: "AutoMigrate",
					Params: map[string]any{
					},
					Func: AppSystemModels.Book{},
				},
			},
		},
		{
			Name: "app/system/web/test.go",
			Annotations: []*annotation.Annotation{
				{
					Name: "Route",
					Params: map[string]any{
					},
					Func: AppSystemWeb.Test,
				},
			},
		},
	}
}
